### Listar todas las tareas
GET http://localhost:3000/todos?completed=0&fecha=2025-10-10

### Listar una tarea por id
GET http://localhost:3000/todos/80a996dc-b520-11f0-8c5c-2ea2e8af62fb

### Crear una tarea
POST http://localhost:3000/todos
Content-Type: application/json

{
    "title":"Tercera tarea creada",
    "description":"Creada con named params",
    "completed": false
}

### Actualizar una tarea
PUT http://localhost:3000/todos/10
Content-Type: application/json

{
    "title":"Modificacion",
    "description": "Pendiente de desplegar a prod",
    "completed": false
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"jealvarengar@unah.edu.hn",
    "password": "Pendiente de desplegar a prod"
}


### Login
PUT http://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwZGI3NTAxLWI0NTYtMTFmMC04ZjgzLTJlYTJlOGFmNjJmYiIsImVtYWlsIjoiamVhbHZhcmVuZ2FyQHVuYWguZWR1LmhuIiwiaWF0IjoxNzYyMjk5MzQ0LCJleHAiOjE3NjIyOTk1MjR9.I7rXOJjZ44DgilzQwsqYyD4HzkPPLiV8jiqJ4Bep27A

{
    "password":"jealvarengar@unah.edu.hn",
    "confirm_password": "Pendiente de desplegar a prod"
}